/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package service;

import database.Config;
import form.JTextFieldHintUI;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.sql.*;
import javax.swing.table.DefaultTableModel;


public class Pegawai extends javax.swing.JInternalFrame {
    
   
    public Pegawai() {
        initComponents();
        showHint();
        showDataPegawai();
        panel_data_pegawai.setVisible(true);
        panel_form_pegawai.setVisible(false);
        setVisibleComponent(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    void setColor(JPanel panel) {
        panel.setBackground(new Color(179, 201, 201));
    }
    
    void resetColor(JPanel panel) {
        panel.setBackground(new Color(192,212,212));
    }
    
    public void showHint() {
        tf_idpegawai.setUI(new JTextFieldHintUI("Masukan ID Pegawai..", Color.GRAY));
        tf_nama.setUI(new JTextFieldHintUI("Masukan Nama..", Color.GRAY));
        tf_alamat.setUI(new JTextFieldHintUI("Masukan Alamat..", Color.GRAY));
        tf_caripegawai.setUI(new JTextFieldHintUI("Silahkan Masukan Data yang ingin dicari..", Color.GRAY));
    }
    
    
    public void clearComponents() {
        tf_idpegawai.setText("");
        tf_nama.setText("");
        cb_jk.setSelectedIndex(0);
        tf_alamat.setText("");
    }
    
    public void addDataPegawai() {
        String jenis_kelamin = null;
        try {
            Connection conn = (Connection) Config.configDB();
            
            Statement state = conn.createStatement();
            
            if (cb_jk.getSelectedIndex() == 1) {
                jenis_kelamin = "L";
            } else 
                if (cb_jk.getSelectedIndex() == 2) {
                    jenis_kelamin = "P";
                }
            
            String sql = "INSERT INTO pegawai VALUES('"+ tf_idpegawai.getText() +"', '"+ tf_nama.getText() +"', '" + jenis_kelamin + "', '" + tf_alamat.getText() +"')";
            
            state.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data Success Added");
            clearComponents();
            state.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error : " + e);
        }
    }
    
    public void showDataPegawai() {
        DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn("No");
        model.addColumn("ID Pegawai");
        model.addColumn("Nama");
        model.addColumn("Jenis kelamin");
        model.addColumn("Alamat");
        
        int no = 1;
        try {
            Connection conn = (Connection) Config.configDB();
            Statement state = conn.createStatement();
            String sql = "SELECT * FROM pegawai ORDER BY id_pegawai ASC";
            
            ResultSet res = state.executeQuery(sql);
            
                    
            while (res.next()) {
                
                model.addRow(new Object [] {
                    no++,
                    res.getString(1),
                    res.getString(2),
                    res.getString(3),
                    res.getString(4)
                });
                tb_pegawai.setModel(model);
            }
            state.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error : " + e);
        }
    }
    
    
    public void cariData() {
        DefaultTableModel model = new DefaultTableModel();
        String cari = tf_caripegawai.getText();
        
        model.addColumn("No");
        model.addColumn("ID Pegawai");
        model.addColumn("Nama");
        model.addColumn("Jenis kelamin");
        model.addColumn("Alamat");
        
        int lengthRow = model.getRowCount();
        for (int n=0; n<lengthRow; n++) {
            model.removeRow(n);
        }
        int no = 1;
        try {
            Connection conn = (Connection) Config.configDB();
            Statement state = conn.createStatement();
            String sql = "SELECT * FROM pegawai WHERE nama LIKE'%"+ tf_caripegawai.getText() +"%'";
            
            ResultSet res = state.executeQuery(sql);
            
                    
            while (res.next()) {
                model.addRow(new Object [] {
                    no++,
                    res.getString(1),
                    res.getString(2),
                    res.getString(3),
                    res.getString(4)
                });
                tb_pegawai.setModel(model);
            }
            state.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error : " + e);
        } 
    }
    
    public void setVisibleComponent(Boolean b) {
        tf_idpegawaiupdate.setVisible(b);
        tf_namaupdate.setVisible(b);
        tf_alamatupdate.setVisible(b);
        cb_jkupdate.setVisible(b);
        tv_rincian_data_pegawai.setVisible(b);
        btn_update.setVisible(b);
        btn_hapus.setVisible(b);
        tv_rincian_id_pegawaii.setVisible(b);
        tv_rincian_nama.setVisible(b);
        tv_rincian_alamat.setVisible(b);
        tv_rincian_jk.setVisible(b);
    }
    
    public void updateDataPegawai() {
        try {
            String sql = "UPDATE pegawai SET id_pegawai='" + tf_idpegawaiupdate.getText() + 
                    "',nama='" + tf_namaupdate.getText() + 
                    "',jk='" + cb_jkupdate.getSelectedItem() + 
                    "',alamat='" + tf_alamatupdate.getText() + 
                    "' WHERE id_pegawai='" + tf_idpegawaiupdate.getText() + 
                    "'";
            Connection conn = (Connection)Config.configDB();
            PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(this, "Edit Data Berhasil...");
            showDataPegawai();
            setVisibleComponent(false);
            
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        side_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_tambah = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_pegawai = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panel_form_pegawai = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        tf_idpegawai = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tf_nama = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cb_jk = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        tf_alamat = new javax.swing.JTextField();
        btn_reset = new javax.swing.JButton();
        btn_submit = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        panel_data_pegawai = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_pegawai = new javax.swing.JTable();
        tf_caripegawai = new javax.swing.JTextField();
        btn_cari = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tv_rincian_data_pegawai = new javax.swing.JLabel();
        tv_rincian_id_pegawaii = new javax.swing.JLabel();
        tv_rincian_nama = new javax.swing.JLabel();
        tv_rincian_jk = new javax.swing.JLabel();
        tv_rincian_alamat = new javax.swing.JLabel();
        tf_namaupdate = new javax.swing.JTextField();
        tf_idpegawaiupdate = new javax.swing.JTextField();
        tf_alamatupdate = new javax.swing.JTextField();
        cb_jkupdate = new javax.swing.JComboBox<>();
        btn_update = new javax.swing.JButton();

        setBackground(new java.awt.Color(220, 228, 228));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_panel.setBackground(new java.awt.Color(192, 212, 212));

        jLabel1.setFont(new java.awt.Font("Quicksand SemiBold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pegawai");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Quicksand Medium", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Interface Guidelanes");

        jLabel4.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(230, 247, 248));
        jLabel4.setText("Form ");

        btn_tambah.setBackground(new java.awt.Color(192, 212, 212));
        btn_tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_tambahMousePressed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add_white.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Quicksand SemiBold", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tambah Pegawai");

        javax.swing.GroupLayout btn_tambahLayout = new javax.swing.GroupLayout(btn_tambah);
        btn_tambah.setLayout(btn_tambahLayout);
        btn_tambahLayout.setHorizontalGroup(
            btn_tambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_tambahLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        btn_tambahLayout.setVerticalGroup(
            btn_tambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_tambahLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(btn_tambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(230, 247, 248));
        jLabel7.setText("Data ");

        btn_pegawai.setBackground(new java.awt.Color(192, 212, 212));
        btn_pegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_pegawaiMousePressed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/people_white.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Quicksand SemiBold", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Data Pegawai");

        javax.swing.GroupLayout btn_pegawaiLayout = new javax.swing.GroupLayout(btn_pegawai);
        btn_pegawai.setLayout(btn_pegawaiLayout);
        btn_pegawaiLayout.setHorizontalGroup(
            btn_pegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_pegawaiLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_pegawaiLayout.setVerticalGroup(
            btn_pegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_pegawaiLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(btn_pegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addContainerGap())
        );

        javax.swing.GroupLayout side_panelLayout = new javax.swing.GroupLayout(side_panel);
        side_panel.setLayout(side_panelLayout);
        side_panelLayout.setHorizontalGroup(
            side_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_tambah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_pegawai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(side_panelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(side_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(side_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addComponent(jLabel7)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        side_panelLayout.setVerticalGroup(
            side_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(side_panelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(45, 45, 45)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_pegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(333, Short.MAX_VALUE))
        );

        getContentPane().add(side_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 200, 640));

        panel_form_pegawai.setBackground(new java.awt.Color(220, 228, 228));
        panel_form_pegawai.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Quicksand Medium", 1, 14)); // NOI18N
        jLabel10.setText("ID Pegawai");
        panel_form_pegawai.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        tf_idpegawai.setFont(new java.awt.Font("Quicksand SemiBold", 0, 12)); // NOI18N
        tf_idpegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idpegawaiActionPerformed(evt);
            }
        });
        tf_idpegawai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_idpegawaiKeyPressed(evt);
            }
        });
        panel_form_pegawai.add(tf_idpegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 350, -1));

        jLabel11.setFont(new java.awt.Font("Quicksand Medium", 1, 14)); // NOI18N
        jLabel11.setText("Jenis Kelamin");
        panel_form_pegawai.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        tf_nama.setFont(new java.awt.Font("Quicksand SemiBold", 0, 12)); // NOI18N
        panel_form_pegawai.add(tf_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 350, -1));

        jLabel12.setFont(new java.awt.Font("Quicksand Medium", 1, 14)); // NOI18N
        jLabel12.setText("Nama");
        panel_form_pegawai.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        cb_jk.setFont(new java.awt.Font("Quicksand Medium", 0, 12)); // NOI18N
        cb_jk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jenis Kelamin", "Laki-laki", "Perempuan" }));
        panel_form_pegawai.add(cb_jk, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 130, -1));

        jLabel13.setFont(new java.awt.Font("Quicksand Medium", 1, 14)); // NOI18N
        jLabel13.setText("Alamat");
        panel_form_pegawai.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        tf_alamat.setFont(new java.awt.Font("Quicksand SemiBold", 0, 12)); // NOI18N
        panel_form_pegawai.add(tf_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 350, -1));

        btn_reset.setFont(new java.awt.Font("Quicksand Medium", 0, 12)); // NOI18N
        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        panel_form_pegawai.add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, -1, -1));

        btn_submit.setFont(new java.awt.Font("Quicksand Medium", 0, 12)); // NOI18N
        btn_submit.setText("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });
        panel_form_pegawai.add(btn_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, -1, -1));

        jLabel14.setFont(new java.awt.Font("Quicksand SemiBold", 0, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Form Pegawai");
        panel_form_pegawai.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        getContentPane().add(panel_form_pegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 640, 590));

        panel_data_pegawai.setBackground(new java.awt.Color(220, 228, 228));

        tb_pegawai.setFont(new java.awt.Font("Quicksand Medium", 0, 12)); // NOI18N
        tb_pegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "Nama", "Jenis Kelamin", "Alamat"
            }
        ));
        tb_pegawai.setGridColor(new java.awt.Color(255, 255, 255));
        tb_pegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_pegawaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_pegawai);

        tf_caripegawai.setFont(new java.awt.Font("Quicksand SemiBold", 0, 12)); // NOI18N
        tf_caripegawai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_caripegawaiKeyPressed(evt);
            }
        });

        btn_cari.setText("Cari");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(220, 228, 228));

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Quicksand SemiBold", 0, 36)); // NOI18N
        jLabel15.setText("Data Pegawai");

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Quicksand Light", 1, 18)); // NOI18N
        jLabel16.setText("Interface Guidlanes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(252, 252, 252))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel18.setFont(new java.awt.Font("Quicksand SemiBold", 0, 12)); // NOI18N
        jLabel18.setText("Ketik Nama Pegawai untuk Mencari Data Pegawai:");

        tv_rincian_data_pegawai.setFont(new java.awt.Font("Quicksand SemiBold", 0, 12)); // NOI18N
        tv_rincian_data_pegawai.setText("Rincian Data Pegawai");

        tv_rincian_id_pegawaii.setFont(new java.awt.Font("Quicksand SemiBold", 0, 12)); // NOI18N
        tv_rincian_id_pegawaii.setText("ID Pegawai");

        tv_rincian_nama.setFont(new java.awt.Font("Quicksand SemiBold", 0, 12)); // NOI18N
        tv_rincian_nama.setText("Nama");

        tv_rincian_jk.setFont(new java.awt.Font("Quicksand SemiBold", 0, 12)); // NOI18N
        tv_rincian_jk.setText("Jenis Kelamin");

        tv_rincian_alamat.setFont(new java.awt.Font("Quicksand SemiBold", 0, 12)); // NOI18N
        tv_rincian_alamat.setText("Alamat");

        tf_namaupdate.setFont(new java.awt.Font("Quicksand SemiBold", 0, 12)); // NOI18N

        tf_idpegawaiupdate.setBackground(new java.awt.Color(234, 246, 248));
        tf_idpegawaiupdate.setFont(new java.awt.Font("Quicksand SemiBold", 0, 12)); // NOI18N

        tf_alamatupdate.setFont(new java.awt.Font("Quicksand SemiBold", 0, 12)); // NOI18N

        cb_jkupdate.setFont(new java.awt.Font("Quicksand Medium", 0, 12)); // NOI18N
        cb_jkupdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "L", "P" }));

        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_data_pegawaiLayout = new javax.swing.GroupLayout(panel_data_pegawai);
        panel_data_pegawai.setLayout(panel_data_pegawaiLayout);
        panel_data_pegawaiLayout.setHorizontalGroup(
            panel_data_pegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_data_pegawaiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_update)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_hapus)
                .addGap(57, 57, 57))
            .addGroup(panel_data_pegawaiLayout.createSequentialGroup()
                .addGroup(panel_data_pegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_data_pegawaiLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(panel_data_pegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(panel_data_pegawaiLayout.createSequentialGroup()
                                .addComponent(tf_caripegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btn_cari))))
                    .addGroup(panel_data_pegawaiLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(panel_data_pegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tv_rincian_data_pegawai)
                            .addGroup(panel_data_pegawaiLayout.createSequentialGroup()
                                .addGroup(panel_data_pegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tv_rincian_nama)
                                    .addComponent(tv_rincian_id_pegawaii)
                                    .addComponent(tv_rincian_jk)
                                    .addComponent(tv_rincian_alamat))
                                .addGap(29, 29, 29)
                                .addGroup(panel_data_pegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_idpegawaiupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_namaupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_alamatupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_jkupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(114, Short.MAX_VALUE))
            .addGroup(panel_data_pegawaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        panel_data_pegawaiLayout.setVerticalGroup(
            panel_data_pegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_data_pegawaiLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_data_pegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_caripegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cari))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_data_pegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_hapus)
                    .addComponent(btn_update))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tv_rincian_data_pegawai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_data_pegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tv_rincian_id_pegawaii)
                    .addComponent(tf_idpegawaiupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_data_pegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tv_rincian_nama)
                    .addComponent(tf_namaupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_data_pegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tv_rincian_jk)
                    .addComponent(cb_jkupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_data_pegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tv_rincian_alamat)
                    .addComponent(tf_alamatupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(panel_data_pegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahMousePressed
        // TODO add your handling code here:
        setColor(btn_tambah);
        panel_form_pegawai.setVisible(true);
        panel_data_pegawai.setVisible(false);
        resetColor(btn_pegawai);
    }//GEN-LAST:event_btn_tambahMousePressed

    private void btn_pegawaiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pegawaiMousePressed
        // TODO add your handling code here:
        showDataPegawai();
        setColor(btn_pegawai);
        panel_form_pegawai.setVisible(false);
        panel_data_pegawai.setVisible(true);
        resetColor(btn_tambah);
    }//GEN-LAST:event_btn_pegawaiMousePressed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        resetColor(btn_tambah);
        
        resetColor(btn_pegawai);
    }//GEN-LAST:event_jLabel1MousePressed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        clearComponents();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void tf_idpegawaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_idpegawaiKeyPressed
        // TODO add your handling code here:
        String idTamu = tf_idpegawai.getText();
        
        int length = idTamu.length();
        if ( length < 4 ) {
            tf_idpegawai.setEditable(true);
        } else 
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE ) {
                tf_idpegawai.setEditable(true);
            } 
        else {
            tf_idpegawai.setEditable(false);
        }
    }//GEN-LAST:event_tf_idpegawaiKeyPressed

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:
        if (tf_nama.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Data Nama Tidak Boleh Kosong");
        } else 
            if (tf_alamat.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Data Alamat Tidak Boleh Kosong");
            }
            else {
                addDataPegawai();
            }
    }//GEN-LAST:event_btn_submitActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        // TODO add your handling code here:
        cariData();
        setVisibleComponent(false);
    }//GEN-LAST:event_btn_cariActionPerformed

    private void tf_caripegawaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_caripegawaiKeyPressed
        // TODO add your handling code here:
        cariData();
        setVisibleComponent(false);
        if (tf_caripegawai.getText() == "") {
            showDataPegawai();
        }
    }//GEN-LAST:event_tf_caripegawaiKeyPressed

    private void tb_pegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_pegawaiMouseClicked
        // TODO add your handling code here:
        setVisibleComponent(true);
        int baris = tb_pegawai.rowAtPoint(evt.getPoint());
        
        String id = tb_pegawai.getValueAt(baris, 1).toString();
        tf_idpegawaiupdate.setText(id);
        tf_idpegawaiupdate.setEditable(false);
        
        String nama = tb_pegawai.getValueAt(baris, 2).toString();
        tf_namaupdate.setText(nama);
        
        String jenisKelamin = tb_pegawai.getValueAt(baris, 3).toString();
        cb_jkupdate.setSelectedItem(jenisKelamin);
        
        String alamat = tb_pegawai.getValueAt(baris, 4).toString();
        tf_alamatupdate.setText(alamat);
    }//GEN-LAST:event_tb_pegawaiMouseClicked

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        int opsi = JOptionPane.showConfirmDialog(null, "Benarkah anda ingin menghapus Data?");
        if (opsi == JOptionPane.YES_OPTION)  {
            try {
                String sql = "DELETE FROM pegawai WHERE id_pegawai='"+ tf_idpegawaiupdate.getText() +"'";
                Connection conn = (Connection)Config.configDB();
                PreparedStatement pstm = conn.prepareStatement(sql);
                pstm.execute();
                JOptionPane.showMessageDialog(this, "Hapus Data Berhasil...");
                showDataPegawai();
                setVisibleComponent(false);
            }
            catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Data tidak jadi dihapus");
        }
        
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        if (tf_namaupdate.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Data Nama Tidak Boleh Kosong");
        } else 
            if (tf_alamatupdate.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Data Alamat Tidak Boleh Kosong");
            }
            else {
                updateDataPegawai();
            }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void tf_idpegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idpegawaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_idpegawaiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JPanel btn_pegawai;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_submit;
    private javax.swing.JPanel btn_tambah;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cb_jk;
    private javax.swing.JComboBox<String> cb_jkupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_data_pegawai;
    private javax.swing.JPanel panel_form_pegawai;
    private javax.swing.JPanel side_panel;
    private javax.swing.JTable tb_pegawai;
    private javax.swing.JTextField tf_alamat;
    private javax.swing.JTextField tf_alamatupdate;
    private javax.swing.JTextField tf_caripegawai;
    private javax.swing.JTextField tf_idpegawai;
    private javax.swing.JTextField tf_idpegawaiupdate;
    private javax.swing.JTextField tf_nama;
    private javax.swing.JTextField tf_namaupdate;
    private javax.swing.JLabel tv_rincian_alamat;
    private javax.swing.JLabel tv_rincian_data_pegawai;
    private javax.swing.JLabel tv_rincian_id_pegawaii;
    private javax.swing.JLabel tv_rincian_jk;
    private javax.swing.JLabel tv_rincian_nama;
    // End of variables declaration//GEN-END:variables
}
